package com.android.sitbak.network

object ApiTags {

    const val LOGIN = "Login"
    const val REGISTER = "Register"
    const val EMAIL_PHONE_CONFIRMATION = "EmailPhoneConfirmation"
    const val ADD_UPDATE_PHONE = "AddUpdatePhone"
    const val ADD_UPDATE_PHOTO = "AddUpdatePhoto"
    const val ADD_USER_LOCATION = "AddUserLocation"
    const val NINETEEN_PLUS = "NineteenPlus"
    const val LOGOUT = "Logout"
    const val DELETE_ACCOUNT = "DeleteAccount"
    const val RECOVER_BY_EMAIL = "RecoverByEmail"
    const val RECOVER_BY_PHONE = "RecoverByPhone"
    const val UPDATE_PASSWORD = "UpdatePassword"
    const val UPDATE_EMAIL = "UpdateEmail"
    const val RESET_PASSWORD = "ResetPassword"
    const val RESEND_OTP = "ResendOtp"
    const val GET_USER_LOCATIONS = "GetUserLocations"
    const val DELETE_USER_LOCATION = "DeleteUserLocations"
    const val SET_AS_DEFAULT_LOCATION = "SetAsDefaultLocations"
    const val GET_FAQ = "GetFAQ"
    const val GET_NEWS = "GetNews"
    const val GET_CATEGORIES = "GetCategories"
    const val GET_STORES = "GetStores"
    const val GET_STORES_SEARCH = "GetStoresSearch"
    const val GET_PAST_ORDERS = "GetPastOrders"
    const val GET_ACTIVE_ORDERS = "GetActiveOrders"
    const val GET_PROFILE = "GetProfile"
    const val GET_STORE_PRODUCTS = "GetStoreProducts"
    const val GET_PRODUCT_CATEGORIES = "GetProductCategories"
    const val GET_STRAING_TYPES = "GetStraingTypes"
    const val ADD_USER_CARD = "AddUserCard"
    const val DELETE_USER_CARD = "DeleteUserCard"
    const val GET_USER_CARDS = "GetUserCards"
    const val UPDATE_USER_DEFAULT_CARD = "UpdateUserDefaultCard"
    const val GET_TERMS_CONDITION = "GetTermsCondition"
    const val GET_PRIVACY = "GetPrivacy"
    const val SEND_CHAT = "SendChat"
    const val GET_CHAT = "GetChat"
    const val SET_FAV_ORDER = "SetFavOrder"
    const val GET_NOTIFICATIONS = "GetNotification"
    const val GET_CART = "GetCart"
    const val POST_ORDER_RATING = "PostOrderRating"

}